#3045: Encoding Cookie Name Values
webdriverio-boneyard/v4 pull request #2
Opened 2018-12-13 04:47 UTC by dmhalejr

## Proposed changes
Proposed solution for https://github.com/webdriverio/webdriverio/issues/3045

## Types of changes
- [x] Bugfix (non-breaking change which fixes an issue) [removes encoding error reported]
- [x] New feature (non-breaking change which adds functionality) [set double encoding on get/set/delete cookie actions)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist
- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [ ] I have proposed the same patch to the new [v5](https://github.com/webdriverio/v5) repository

### Reviewers: @christian-bromann

2018-12-13 09:29 UTC, christian-bromann requested changes
some comments

2018-12-13 09:29 UTC, christian-bromann commented on lib/commands/setCookie.js
> +    return this.cookie('POST', Object.assign({}, cookieObj, { name: encodeURIComponent(encodeURIComponent((cookieObj.name)))}))
better:
```js
return this.cookie(
    'POST',
    Object.assign(
        {},
        cookieObj,
        { name: encodeURIComponent(encodeURIComponent(name)) }
    )
)
```

2018-12-13 09:29 UTC, christian-bromann commented on test/spec/cookie.js
> +        } catch (e) {
if the setCookie command doesn't fail for some reason there won't be any assertion

2018-12-13 09:29 UTC, christian-bromann commented on test/spec/cookie.js
> +        } catch (e) {
same

2018-12-13 09:29 UTC, christian-bromann commented on test/spec/cookie.js
> +        } catch (e) {
same

2018-12-13 09:29 UTC, christian-bromann commented on test/spec/cookie.js
> +        cookie.name.should.be.equal(encodeURIComponent(encodeURIComponent('/:?test2')))
I think it is better to hardcode the result here, so instead of
```js
encodeURIComponent(encodeURIComponent('/:?test2'))
```
let's do 
```
%252F%253A%253Ftest2
```

2018-12-13 09:29 UTC, christian-bromann commented on test/spec/cookie.js
> +        cookie.name.should.be.equal(encodeURIComponent(encodeURIComponent("~!@#$%^&*()_+-={}|[]\:\"'<>?,./")))
same

2018-12-14 04:29 UTC, dmhalejr commented
@christian-bromann Up for your additional review. My apologies if you are getting multiple pings regarding this open PR. My intent is to do nothing more to make you aware. As an outside contributor what is the best way to let you know "your changes requested have been completed"? Is it just marking the conversation resolved?

Thanks for all you do!

2019-03-04 09:33 UTC, christian-bromann approved these changes
👍

2019-03-04 09:33 UTC, merged