Change locator strategy of hash (#) to css selector instead of id
webdriverio-boneyard/v4 pull request #5
Opened 2019-01-02 22:16 UTC by fijijavis

## Proposed changes

[//]: # This change addresses issue [2780](https://github.com/webdriverio/webdriverio/issues/2780) where By.id location strategy is being removed since it is not part of the w3c spec.   With hash ```#``` already working for css selectors, this should be a transparent change to existing tests

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [X] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)
- [ ] I have proposed the same patch to the new [v5](https://github.com/webdriverio/v5) repository

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### Reviewers: @christian-bromann

2019-01-02 22:33 UTC, emilyrohrbough commented
Is this really the only changed needed to use css id selector syntax for newer selenium drivers?

2019-01-02 22:52 UTC, fijijavis commented
@emilyrohrbough I believe so.  ```findElementStrategy.js``` file is responsible for determining which locator strategy to send as the ```using``` portion of the POST body.

pre-change:

```
COMMAND POST "/wd/hub/session/0f10e8f6-066d-4a9c-bced-24ccf21cc2f7/elements" DATA {"using":"id","value":"my_selector"}
```

post-change:
```
COMMAND POST "/wd/hub/session/0f10e8f6-066d-4a9c-bced-24ccf21cc2f7/elements" DATA {"using":"css selector","value":"#my_selector"}
```

2019-01-02 22:54 UTC, emilyrohrbough commented
🤦‍♀️ oh nice catch! 

I've actually spent the last few days creating a custom linter to discourage css id selector syntax with auto-fixes because this was about to become a huge problem for our projects. Guess I can throw that out now 😄

2019-01-03 14:40 UTC, fijijavis commented
@christian-bromann Let me know what you think.  Thanks

2019-01-03 17:24 UTC, emilyrohrbough approved these changes
Tested these changes in our project and this resolves the driver crashes we were experiencing when using css id selectors.

2019-01-03 17:35 UTC, christian-bromann requested changes
One comment.

2019-01-03 17:35 UTC, christian-bromann commented on package.json
> +  "version": "4.14.2",
The version is bumped automatically. Please revert this change.

2019-01-03 18:48 UTC, fijijavis commented on package.json
> +  "version": "4.14.2",
@christian-bromann Reverted.  Not sure what I was thinking.

2019-01-03 21:24 UTC, christian-bromann approved these changes
👍 thanks, I will make a release tomorrow.

2019-01-03 21:28 UTC, fijijavis commented
awesome.  thank you too!

2019-01-04 19:14 UTC, fijijavis commented
@christian-bromann any idea when you might be able to do a release?

2019-01-07 15:26 UTC, fijijavis commented
@christian-bromann just checking in.  thanks

2019-01-08 14:49 UTC, fijijavis commented
@christian-bromann I hate to be a pest, but we really need this changed published.

2019-01-10 23:35 UTC, christian-bromann approved these changes
👍

2019-01-10 23:35 UTC, merged

2019-01-27 14:02 UTC, usmonster commented
Hello!

Just wanted to make you aware that this is actually a breaking change for those who relied on the previous behavior of `#`-prefixed locators to default to the `id` strategy, e.g. for appium/native mobile app tests.

(We were taken by surprise with this update, as there's no changelog, no tag, and no mention on the [Releases](https://github.com/webdriverio/webdriverio/releases) page... 🙃)

I'd request either implementing a compatible solution (something like `using = isMobile ? 'id' : 'css selector'`) or simply reverting that change, and then please make a new 4.14 patch release (with a changelog, please). Thanks!